Adding deploymnet.json to enable CI
vtex/checkout-ui-tests pull request #79
Opened 2021-02-03 14:07 UTC by tellesnobrega

Enabling CI for this repo.

2021-02-03 16:53 UTC, FelipeNascimento approved these changes

2021-02-03 17:05 UTC, FelipeNascimento requested changes
Dockerfile path is invalid as CI said:
`Error response from daemon: unexpected error reading Dockerfile: read /var/lib/docker/tmp/docker-builder556778397/dockerfiles/stable: is a directory`

2021-02-03 17:05 UTC, FelipeNascimento commented on .vtex/deployment.json
> +        "DOCKER_FILE": "dockerfiles/stable"
It's a directory and must to have the full path of dockerfile

2021-02-03 17:06 UTC, lucasecdb approved these changes

2021-02-03 18:34 UTC, wdsrocha approved these changes

2021-02-03 19:28 UTC, wdsrocha commented
anyone knows how to re-run the Jenkins CI?

2021-02-03 19:30 UTC, wdsrocha requested changes
Same as Felipe Nascimento pointed out

2021-02-04 15:14 UTC, FelipeNascimento approved these changes

2021-02-04 18:09 UTC, wdsrocha approved these changes

2021-02-08 12:39 UTC, merged